In [3]:
%matplotlib inline

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [4]:
import tensorflow as tf

In [28]:
from sklearn import metrics
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split


from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

In [9]:
df1 = pd.read_csv("ILINet.csv")
df1.head(2)

,REGION,YEAR,WEEK,%WEIGHTEDILI,%UNWEIGHTEDILI,AGE 0-4,AGE 25-49,AGE 25-64,AGE 5-24,AGE 50-64,AGE 65,ILITOTAL,NUM. OF PROVIDERS,TOTAL PATIENTS
0,Alabama,2010,40,X,2.13477,X,X,X,X,X,X,249,35,11664
1,Alaska,2010,40,X,0.875146,X,X,X,X,X,X,15,7,1714

In [10]:
df1 = pd.read_csv("ILINet.csv")
del df1["%WEIGHTEDILI"]
del df1["AGE 0-4"]
del df1["AGE 25-49"]
del df1["AGE 25-64"]
del df1["AGE 5-24"]
del df1["AGE 50-64"]
del df1["AGE 65"]
del df1["ILITOTAL"]
del df1["NUM. OF PROVIDERS"]
del df1["TOTAL PATIENTS"]
# del df1["YEAR"]
df1.head(2)

    REGION  YEAR  WEEK %UNWEIGHTEDILI
0  Alabama  2010    40        2.13477
1   Alaska  2010    40       0.875146

In [11]:
# rows with value of X replaced by zero
df = df1.replace(r"X","0")
df = df.rename(columns={"%UNWEIGHTEDILI": "PERCENTAGE_ILI"})
df = df[["REGION",
         "YEAR", 
         "WEEK", "PERCENTAGE_ILI"]]
df = df.set_index(["REGION"])
df.head()

            YEAR  WEEK PERCENTAGE_ILI
REGION
Alabama     2010    40        2.13477
Alaska      2010    40       0.875146
Arizona     2010    40       0.674721
Arkansas    2010    40       0.696056
California  2010    40        1.95412

In [12]:
df["WEEK"].unique()

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 53], dtype=int64)

In [13]:
wk40 = df[df["WEEK"] == 40]
wk41 = df[df["WEEK"] == 41]
wk42 = df[df["WEEK"] == 42]
wk43 = df[df["WEEK"] == 43]
wk44 = df[df["WEEK"] == 44]
wk45 = df[df["WEEK"] == 45]
wk46 = df[df["WEEK"] == 46]
wk47 = df[df["WEEK"] == 47]
wk48 = df[df["WEEK"] == 48]
wk49 = df[df["WEEK"] == 49]
wk50 = df[df["WEEK"] == 50]
wk51 = df[df["WEEK"] == 51]
wk52 = df[df["WEEK"] == 52]


wk1 = df[df["WEEK"] == 1]
wk2 = df[df["WEEK"] == 2]
wk3 = df[df["WEEK"] == 3]
wk4 = df[df["WEEK"] == 4]
wk5 = df[df["WEEK"] == 5]
wk6 = df[df["WEEK"] == 6]
wk7 = df[df["WEEK"] == 7]
wk8 = df[df["WEEK"] == 8]
wk9 = df[df["WEEK"] == 9]
wk10 = df[df["WEEK"] == 10]

wk11 = df[df["WEEK"] == 11]
wk12 = df[df["WEEK"] == 12]
wk13 = df[df["WEEK"] == 13]
wk14 = df[df["WEEK"] == 14]
wk15 = df[df["WEEK"] == 15]
wk16 = df[df["WEEK"] == 16]
wk17 = df[df["WEEK"] == 17]
wk18 = df[df["WEEK"] == 18]
wk19 = df[df["WEEK"] == 19]
wk20 = df[df["WEEK"] == 20]

In [14]:
wk40 = wk40.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week40"})
wk41 = wk41.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week41"})
wk42 = wk42.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week42"})
wk43 = wk43.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week43"})
wk44 = wk44.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week44"})
wk45 = wk45.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week45"})
wk46 = wk46.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week46"})
wk47 = wk47.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week47"})
wk48 = wk48.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week48"})
wk49 = wk49.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week49"})
wk50 = wk50.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week50"})
wk51 = wk51.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week51"})
wk52 = wk52.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week52"})


wk1 = wk1.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week1"})
wk2 = wk2.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week2"})
wk3 = wk3.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week3"})
wk4 = wk4.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week4"})
wk5 = wk5.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week5"})
wk6 = wk6.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week6"})
wk7 = wk7.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week7"})
wk8 = wk8.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week8"})
wk9 = wk9.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week9"})
wk10 = wk10.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week10"})

wk11 = wk11.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week11"})
wk12 = wk12.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week12"})
wk13 = wk13.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week13"})
wk14 = wk14.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week14"})
wk15 = wk15.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week15"})
wk16 = wk16.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week16"})
wk17 = wk17.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week17"})
wk18 = wk18.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week18"})
wk19 = wk19.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week19"})
wk20 = wk20.rename(columns={"PERCENTAGE_ILI": "Percentage_ill_week20"})

In [15]:
del wk40["WEEK"]
del wk41["WEEK"]
del wk42["WEEK"]
del wk43["WEEK"]
del wk44["WEEK"]
del wk45["WEEK"]
del wk46["WEEK"]
del wk47["WEEK"]
del wk48["WEEK"]
del wk49["WEEK"]
del wk50["WEEK"]
del wk51["WEEK"]
del wk52["WEEK"]

del wk1["WEEK"]
del wk2["WEEK"]
del wk3["WEEK"]
del wk4["WEEK"]
del wk5["WEEK"]
del wk6["WEEK"]
del wk7["WEEK"]
del wk8["WEEK"]
del wk9["WEEK"]
del wk10["WEEK"]

del wk11["WEEK"]
del wk12["WEEK"]
del wk13["WEEK"]
del wk14["WEEK"]
del wk15["WEEK"]
del wk16["WEEK"]
del wk17["WEEK"]
del wk18["WEEK"]
del wk19["WEEK"]
del wk20["WEEK"]

In [56]:
# r = pd.concat([wk40, 
# wk41], axis=1, sort=False)
# r

In [16]:
flu_df = pd.concat([wk40, 
wk41, 
wk42, 
wk43,  
wk44, 
wk45, 
wk46, 
wk47, 
wk48, 
wk49, 
wk50, 
wk51, 
wk52, 
wk1, 
wk2, 
wk3,  
wk4, 
wk5, 
wk6, 
wk7, 
wk8, 
wk9, 
wk10,         
wk11, 
wk12, 
wk13,  
wk14, 
wk15, 
wk16, 
wk17, 
wk18, 
wk19, 
wk20], axis=1, sort=False)
flu_df.head()

,YEAR,Percentage_ill_week40,YEAR,Percentage_ill_week41,YEAR,Percentage_ill_week42,YEAR,Percentage_ill_week43,YEAR,Percentage_ill_week44,...,YEAR,Percentage_ill_week16,YEAR,Percentage_ill_week17,YEAR,Percentage_ill_week18,YEAR,Percentage_ill_week19,YEAR,Percentage_ill_week20
REGION,,,,,,,,,,,,,,,,,,,,,
Alabama,2010,2.13477,2010,2.05999,2010,1.94224,2010,2.2765,2010,2.83371,...,2011,2.76866,2011,3.28311,2011,3.00455,2011,2.64628,2011,2.46441
Alaska,2010,0.875146,2010,1.12827,2010,0.586042,2010,0.967742,2010,0.683851,...,2011,1.4123,2011,0.854271,2011,0.798122,2011,0.359712,2011,0.306279
Arizona,2010,0.674721,2010,0.749939,2010,0.953365,2010,0.888804,2010,1.18573,...,2011,1.09028,2011,0.835587,2011,0.772679,2011,0.686106,2011,0.569434
Arkansas,2010,0.696056,2010,0.674157,2010,0.514217,2010,0.41365,2010,1.09028,...,2011,0.675676,2011,0.455754,2011,0.630347,2011,0.711744,2011,0.520382
California,2010,1.95412,2010,2.15266,2010,2.24173,2010,1.91748,2010,2.52326,...,2011,2.24199,2011,2.34436,2011,2.14632,2011,2.05279,2011,2.13285

In [17]:
flu_season_start_year = flu_df.iloc[:,0]
# flu_season_start_year

In [18]:
flu_compact_df = pd.DataFrame()
for ix, col in enumerate(flu_df):
    if ix % 2 == 1:
        flu_compact_df[col] = flu_df[col].astype('float')
flu_compact_df.head()

,Percentage_ill_week40,Percentage_ill_week41,Percentage_ill_week42,Percentage_ill_week43,Percentage_ill_week44,Percentage_ill_week45,Percentage_ill_week46,Percentage_ill_week47,Percentage_ill_week48,Percentage_ill_week49,...,Percentage_ill_week11,Percentage_ill_week12,Percentage_ill_week13,Percentage_ill_week14,Percentage_ill_week15,Percentage_ill_week16,Percentage_ill_week17,Percentage_ill_week18,Percentage_ill_week19,Percentage_ill_week20
REGION,,,,,,,,,,,,,,,,,,,,,
Alabama,2.134770,2.059990,1.942240,2.276500,2.833710,3.462240,3.532480,4.276550,4.44043,5.810970,...,4.04606,3.438340,3.17374,2.746590,2.675920,2.768660,3.283110,3.004550,2.646280,2.464410
Alaska,0.875146,1.128270,0.586042,0.967742,0.683851,0.951904,0.962567,0.652316,0.45977,0.797721,...,2.68747,3.024570,2.14376,2.208200,1.365040,1.412300,0.854271,0.798122,0.359712,0.306279
Arizona,0.674721,0.749939,0.953365,0.888804,1.185730,0.945337,1.096650,1.133800,1.42227,2.148350,...,1.32819,0.996642,1.11316,0.997526,0.895053,1.090280,0.835587,0.772679,0.686106,0.569434
Arkansas,0.696056,0.674157,0.514217,0.413650,1.090280,1.197360,1.554620,2.025990,1.39295,1.020640,...,3.26913,2.313620,1.66325,0.850906,0.438757,0.675676,0.455754,0.630347,0.711744,0.520382
California,1.954120,2.152660,2.241730,1.917480,2.523260,2.745620,2.819630,3.161320,2.60631,3.056130,...,4.43790,3.297030,3.20000,2.646830,2.571930,2.241990,2.344360,2.146320,2.052790,2.132850

In [19]:
flu_compact_w_yr_df = flu_compact_df.copy()
flu_compact_w_yr_df['Season'] = flu_season_start_year

In [20]:
flu_compact_w_yr_df.head()

,Percentage_ill_week40,Percentage_ill_week41,Percentage_ill_week42,Percentage_ill_week43,Percentage_ill_week44,Percentage_ill_week45,Percentage_ill_week46,Percentage_ill_week47,Percentage_ill_week48,Percentage_ill_week49,...,Percentage_ill_week12,Percentage_ill_week13,Percentage_ill_week14,Percentage_ill_week15,Percentage_ill_week16,Percentage_ill_week17,Percentage_ill_week18,Percentage_ill_week19,Percentage_ill_week20,Season
REGION,,,,,,,,,,,,,,,,,,,,,
Alabama,2.134770,2.059990,1.942240,2.276500,2.833710,3.462240,3.532480,4.276550,4.44043,5.810970,...,3.438340,3.17374,2.746590,2.675920,2.768660,3.283110,3.004550,2.646280,2.464410,2010
Alaska,0.875146,1.128270,0.586042,0.967742,0.683851,0.951904,0.962567,0.652316,0.45977,0.797721,...,3.024570,2.14376,2.208200,1.365040,1.412300,0.854271,0.798122,0.359712,0.306279,2010
Arizona,0.674721,0.749939,0.953365,0.888804,1.185730,0.945337,1.096650,1.133800,1.42227,2.148350,...,0.996642,1.11316,0.997526,0.895053,1.090280,0.835587,0.772679,0.686106,0.569434,2010
Arkansas,0.696056,0.674157,0.514217,0.413650,1.090280,1.197360,1.554620,2.025990,1.39295,1.020640,...,2.313620,1.66325,0.850906,0.438757,0.675676,0.455754,0.630347,0.711744,0.520382,2010
California,1.954120,2.152660,2.241730,1.917480,2.523260,2.745620,2.819630,3.161320,2.60631,3.056130,...,3.297030,3.20000,2.646830,2.571930,2.241990,2.344360,2.146320,2.052790,2.132850,2010

In [62]:
# flu_compact_w_yr_df.to_csv("output")

In [36]:
# This codes breaks *very easily* and is not well-written.  Please re-factor when you get a chance
# Make sure the number of columns in flu_season_compact_w_yr_df is the same as the number in the denominator on
# the second to last line.  Also, make sure the final number in the line beginning with 'next_season' is one less than 
# the number of columns in flu_season_compact_w_yr_df

# Also, consider iterating over the DataFrame in a better way.  This only is reasonable because the DataFrame is 
# small 

# The 'Season' column *must* be the last column in the DataFrame,
next_season_means = []
for ix in range(len(flu_compact_w_yr_df)):
    next_season = flu_compact_w_yr_df.iat[ix,33]
    state = flu_compact_w_yr_df.index[ix]
    source1_df = flu_compact_w_yr_df.loc[state]
    source_df = source1_df.loc[source1_df['Season'] == next_season]
    next_season_mean = source_df.mean(axis = 1) - next_season / 34
    next_season_means.append(next_season_mean)

In [37]:
# X's are a given season's weekly incidences.
# y's are the averages of all incidences in the same state in the season after the current one (e.g. 2011 for 2010)#

X = flu_compact_df.values
y = np.array(next_season_means)
X.shape, y.shape

((482, 33), (482, 1))

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25, random_state = 0) #25% hold for testing

In [41]:
print(X_train.shape, X_test.shape)

(361, 33) (121, 33)

In [42]:
X_scaler = StandardScaler().fit(X_train)

In [43]:
X_train_scaled = X_scaler.transform(X_train)
X_train_scaled

array([[ 1.23957975,  1.21872505,  0.89899598, ...,  0.49943983,
         0.61281427,  0.42716188],
       [-0.71090898, -0.67846113, -0.41807709, ..., -0.92838962,
        -0.76814771, -0.68778548],
       [-0.50920502, -0.33284353, -0.54957966, ..., -0.58779311,
        -0.27013817, -0.7480719 ],
       ...,
       [-0.09684962, -0.12172152, -0.26800716, ..., -0.73905385,
        -0.95591766, -0.79946137],
       [-0.63770596, -0.11215419, -0.28561392, ..., -0.45100387,
        -0.53149385, -0.53134588],
       [-0.17625297, -0.26686626, -0.20111715, ..., -0.42998146,
        -0.46871117,  0.08834473]])

In [48]:
from tensorflow.contrib import learn