In [26]:
# Import Dependencies
import pandas as pd
import datetime
import time

In [27]:
df1 = pd.read_csv("../FluViewPhase2Data/ILINet.csv")
df1.head(500)

,REGION TYPE,REGION,YEAR,WEEK,%WEIGHTEDILI,%UNWEIGHTED ILI,AGE 0-4,AGE 25-49,AGE 25-64,AGE 5-24,AGE 50-64,AGE 65,ILITOTAL,NUM. OF PROVIDERS,TOTAL PATIENTS
0,States,Alabama,2010,40,X,2.13477,X,X,X,X,X,X,249,35,11664
1,States,Alaska,2010,40,X,0.875146,X,X,X,X,X,X,15,7,1714
2,States,Arizona,2010,40,X,0.674721,X,X,X,X,X,X,172,49,25492
3,States,Arkansas,2010,40,X,0.696056,X,X,X,X,X,X,18,15,2586
4,States,California,2010,40,X,1.95412,X,X,X,X,X,X,632,112,32342
5,States,Colorado,2010,40,X,0.660684,X,X,X,X,X,X,134,14,20282
6,States,Connecticut,2010,40,X,0.0783085,X,X,X,X,X,X,3,12,3831
7,States,Delaware,2010,40,X,0.100125,X,X,X,X,X,X,4,13,3995
8,States,District of Columbia,2010,40,X,2.80877,X,X,X,X,X,X,73,4,2599
9,States,Florida,2010,40,X,X,X,X,X,X,X,X,X,X,X
10,States,Georgia,2010,40,X,1.6049,X,X,X,X,X,X,647,62,40314
11,States,Hawaii,2010,40,X,1.02934,X,X,X,X,X,X,20,18,1943
12,States,Idaho,2010,40,X,0.414938,X,X,X,X,X,X,19,12,4579
13,States,Illinois,2010,40,X,1.28205,X,X,X,X,X,X,505,74,39390
14,States,Indiana,2010,40,X,0.518962,X,X,X,X,X,X,65,44,12525
15,States,Iowa,2010,40,X,0.563063,X,X,X,X,X,X,10,6,1776
16,States,Kansas,2010,40,X,0.442227,X,X,X,X,X,X,39,40,8819
17,States,Kentucky,2010,40,X,0.142932,X,X,X,X,X,X,19,14,13293
18,States,Louisiana,2010,40,X,2.28108,X,X,X,X,X,X,391,41,17141
19,States,Maine,2010,40,X,0.357724,X,X,X,X,X,X,22,30,6150
20,States,Maryland,2010,40,X,1.3192,X,X,X,X,X,X,117,17,8869
21,States,Massachusetts,2010,40,X,0.604621,X,X,X,X,X,X,168,56,27786
22,States,Michigan,2010,40,X,0.671831,X,X,X,X,X,X,98,47,14587
23,States,Minnesota,2010,40,X,0.5748,X,X,X,X,X,X,38,17,6611
24,States,Mississippi,2010,40,X,2.9098,X,X,X,X,X,X,491,42,16874
25,States,Missouri,2010,40,X,1.10176,X,X,X,X,X,X,106,33,9621
26,States,Montana,2010,40,X,0.0371195,X,X,X,X,X,X,1,7,2694
27,States,Nebraska,2010,40,X,2.19978,X,X,X,X,X,X,61,13,2773
28,States,Nevada,2010,40,X,1.66683,X,X,X,X,X,X,175,30,10499
29,States,New Hampshire,2010,40,X,0.0759301,X,X,X,X,X,X,3,21,3951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,States,Arizona,2010,49,X,2.14835,X,X,X,X,X,X,517,53,24065
471,States,Arkansas,2010,49,X,1.02064,X,X,X,X,X,X,44,17,4311
472,States,California,2010,49,X,3.05613,X,X,X,X,X,X,1072,135,35077
473,States,Colorado,2010,49,X,0.809504,X,X,X,X,X,X,154,12,19024
474,States,Connecticut,2010,49,X,0.654897,X,X,X,X,X,X,23,11,3512
475,States,Delaware,2010,49,X,0.361156,X,X,X,X,X,X,9,10,2492
476,States,District of Columbia,2010,49,X,3.26052,X,X,X,X,X,X,100,4,3067
477,States,Florida,2010,49,X,X,X,X,X,X,X,X,X,X,X
478,States,Georgia,2010,49,X,4.48962,X,X,X,X,X,X,1685,62,37531
479,States,Hawaii,2010,49,X,2.42215,X,X,X,X,X,X,42,18,1734
480,States,Idaho,2010,49,X,1.72267,X,X,X,X,X,X,81,13,4702
481,States,Illinois,2010,49,X,1.85288,X,X,X,X,X,X,732,79,39506
482,States,Indiana,2010,49,X,0.949958,X,X,X,X,X,X,112,42,11790
483,States,Iowa,2010,49,X,0.954329,X,X,X,X,X,X,28,10,2934
484,States,Kansas,2010,49,X,0.828437,X,X,X,X,X,X,86,43,10381
485,States,Kentucky,2010,49,X,0.598723,X,X,X,X,X,X,90,15,15032
486,States,Louisiana,2010,49,X,2.80486,X,X,X,X,X,X,492,40,17541
487,States,Maine,2010,49,X,0.435219,X,X,X,X,X,X,26,31,5974
488,States,Maryland,2010,49,X,1.55109,X,X,X,X,X,X,153,20,9864
489,States,Massachusetts,2010,49,X,0.96749,X,X,X,X,X,X,272,54,28114
490,States,Michigan,2010,49,X,0.563399,X,X,X,X,X,X,85,52,15087
491,States,Minnesota,2010,49,X,0.584334,X,X,X,X,X,X,37,17,6332
492,States,Mississippi,2010,49,X,5.33836,X,X,X,X,X,X,878,46,16447
493,States,Missouri,2010,49,X,1.37036,X,X,X,X,X,X,113,31,8246
494,States,Montana,2010,49,X,0.0359454,X,X,X,X,X,X,1,6,2782
495,States,Nebraska,2010,49,X,2.46212,X,X,X,X,X,X,91,16,3696
496,States,Nevada,2010,49,X,3.28279,X,X,X,X,X,X,394,35,12002
497,States,New Hampshire,2010,49,X,0.247015,X,X,X,X,X,X,12,30,4858
498,States,New Jersey,2010,49,X,2.65371,X,X,X,X,X,X,183,24,6896
499,States,New Mexico,2010,49,X,2.32423,X,X,X,X,X,X,200,25,8605

In [35]:
# Create Loop:
#  1.) Go through each row and if the value in Region is unique create a new list and grab its corresponding "%UNWEIGHTED ILI" value.
#  2.) As loop is going if it comes across a similar Region then add the corresponding "%UNWEIGHTED ILI" value to corresponding list.

# selecting rows based on condition 
options = ['40']

rslt_df = df1.loc[(df1['REGION'] == "Alabama") & 
              df1['WEEK'].isin(options)] 
  
rslt_df["%UNWEIGHTED ILI"].mean()

TypeError: Could not convert 2.134772.494861.494041.590441.731742.588752.223981.757211.62738 to numeric