In [38]:
import warnings
warnings.simplefilter('ignore')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import scale

from sklearn.model_selection import train_test_split
from sklearn import decomposition
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier

import seaborn as sns
np.random.seed(0)

In [39]:
flu = pd.read_csv('ILINet.csv')
flu.head()

                                                                                                                                             PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS
REGION TYPE REGION YEAR WEEK % WEIGHTED ILI %UNWEIGHTED ILI AGE 0-4 AGE 25-49 AGE 25-64 AGE 5-24 AGE 50-64 AGE 65 ILITOTAL NUM. OF PROVIDERS                                     TOTAL PATIENTS
National    X      1997 40   1.10148        1.21686         179     X         157       205      X         29     570      192                                                            46842
                        41   1.20007        1.28064         199     X         151       242      X         23     615      191                                                            48023
                        42   1.37876        1.23906         228     X         153       266      X         34     681      219                                                            54961
                        43   1.1992         1.14473         188     X         193       236      X         36     653      213                                                            57044

In [106]:
fluNew = pd.read_csv("ILINet.csv", skiprows =1)
fluNew.columns = fluNew.columns.str.replace(' ', '_')
fluNew.columns = fluNew.columns.str.replace('.', '')
fluNew.columns = fluNew.columns.str.replace('-', '_')
fluNew.columns = fluNew.columns.str.replace('%', '')
fluNew.columns
del fluNew["REGION_TYPE"]
del fluNew["REGION"]
del fluNew["UNWEIGHTED_ILI"]
del fluNew["NUM_OF_PROVIDERS"]
del fluNew["TOTAL_PATIENTS"]
del fluNew["AGE_25_49"]
del fluNew["AGE_50_64"]
fluNew.head(2)

   YEAR  WEEK _WEIGHTED_ILI AGE_0_4 AGE_25_64 AGE_5_24 AGE_65 ILITOTAL
0  1997    40       1.10148     179       157      205     29      570
1  1997    41       1.20007     199       151      242     23      615

In [118]:
fludf = fluNew.replace(r'X','0')
fludf = fluNew[["YEAR", "_WEIGHTED_ILI"]]
fludf = fluNew.set_index(["WEEK"])

In [120]:
fludf.to_csv("flu_based_age")